name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
          
    - name: Setup nuget package
      run: dotnet nuget add source https://nuget.pkg.github.com/alanbarros/index.json -n github -u alanbarros -p ${{secrets.GH_TOKEN}}

    - name: Install dependencies
      run: |  
          cd $GITHUB_WORKSPACE/src/Gcsb.NSwag.Configuration/
          dotnet restore
          
    - name: Build
      run: |  
          cd $GITHUB_WORKSPACE/src/Gcsb.NSwag.Configuration/ 
          dotnet build --configuration Release --no-restore
          
    - name: Build solution and generate NuGet package
      run: |  
        cd $GITHUB_WORKSPACE/src/Gcsb.NSwag.Configuration/
        dotnet pack -c Release -o out
        
    - name: Push generated package to GitHub registry
      run: |  
        cd $GITHUB_WORKSPACE/src/Gcsb.NSwag.Configuration/
        dotnet nuget push out/*.nupkg --source "github" --skip-duplicate --no-symbols true
