name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - working-directory: $GITHUB_WORKSPACE/src/Gcsb.NSwag.Configuration/
    - uses: actions/checkout@v2      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build Soluction
      run: dotnet build --configuration Release --no-restore
          
  config:
    name: "Config Package"
    runs-on: ubuntu-latest
    steps:      
    - name: Setup nuget package
      run: dotnet nuget add source https://nuget.pkg.github.com/alanbarros/index.json -n github -u alanbarros -p ${{secrets.GH_TOKEN}}

    - name: Install dependencies
      run: |  
          cd $GITHUB_WORKSPACE/src/Gcsb.NSwag.Configuration/
          dotnet restore
          
  pack:
    name: "Create Package"
    runs-on: ubuntu-latest
    steps:          
    - name: Generate NuGet package
      run: |  
        cd $GITHUB_WORKSPACE/src/Gcsb.NSwag.Configuration/
        dotnet pack -c Release -o out
        
  push:
    name: "Publish Package"
    runs-on: ubuntu-latest
    steps: 
    - name: Push generated package to GitHub registry
      run: |  
        cd $GITHUB_WORKSPACE/src/Gcsb.NSwag.Configuration/
        dotnet nuget push out/*.nupkg --source "github" --skip-duplicate --no-symbols true
